Repository flick-23/HacktoberFest, pull requests merged in 2021-10, with the labels that each got.

#10 Leetcode Remove Element solution added
  27. LeetCode Problems/remove-element.cpp
Labels: good-first-contribution

#11 More Sorting Codes
  06. Sorting/SelectionSort.cpp
  06. Sorting/merge-sort.cpp
  06. Sorting/quick-sort.cpp
Labels: hacktofest-accepted, good-first-contribution

#14 added 5 medium level String problems and solutions in cpp
  09. String/Edit distance'.cpp
  09. String/Interleaving strings.cpp
  09. String/Ip address.cpp
  09. String/add binary strings.cpp
  09. String/own atoi.cpp
Labels: hacktoberfest, hacktofest-accepted, good-first-contribution

#16 Solution for Leetcode # 44. Wildcard Matching
  27. LeetCode Problems/C#/44. Wildcard Matching/readme.md
  27. LeetCode Problems/C#/44. Wildcard Matching/solution.cs
Labels: hacktoberfest, hacktofest-accepted, good-first-contribution

#17 Add files via upload
  Binary Search Tree.c
Labels: hacktoberfest, hacktofest-accepted, good-first-contribution

#19 Create fibonacci.py
  33. Python Programs/fibonacci.py
Labels: hacktoberfest, hacktofest-accepted, good-first-contribution

#18 added a frontend template of dog tinder website
  34. Front-End Website Templates/TinDog-Start-master/.DS_Store
  34. Front-End Website Templates/TinDog-Start-master/css/.DS_Store
  34. Front-End Website Templates/TinDog-Start-master/css/styles.css
  34. Front-End Website Templates/TinDog-Start-master/images/.DS_Store
  34. Front-End Website Templates/TinDog-Start-master/images/TechCrunch.png
  34. Front-End Website Templates/TinDog-Start-master/images/bizinsider.png
  34. Front-End Website Templates/TinDog-Start-master/images/dog-img.jpg
  34. Front-End Website Templates/TinDog-Start-master/images/iphone6.png
  34. Front-End Website Templates/TinDog-Start-master/images/lady-img.jpg
  34. Front-End Website Templates/TinDog-Start-master/images/mashable.png
  34. Front-End Website Templates/TinDog-Start-master/images/tnw.png
  34. Front-End Website Templates/TinDog-Start-master/index.html
Labels: good first issue, hacktoberfest, hacktofest-accepted, good-first-contribution, hacktoberfest-accepted

#20 Create selectionSort.c
  selectionSort.c
Labels: good first issue, good-first-contribution, hacktoberfest-accepted

#13 Added quick sort
  06. Sorting/QuickSort.cpp
Labels: hacktoberfest, good-first-contribution, hacktoberfest-accepted

#12 4 Algorithm And 5 Question of Arrays
  04. Arrays/1 Find if there is any subarray with sum equal to 0.cpp
  04. Arrays/Find if there is any subarray with sum equal to 0.cpp
  04. Arrays/Minimise the maximum difference between heights [V.IMP].cpp
  04. Arrays/Move all the negative elements to one side of the array.cpp
  04. Arrays/Write a program to cyclically rotate an array by one..cpp
  04. Arrays/find all pairs on integer array whose sum is equal to given number.cpp
  04. Arrays/find common elements In 3 sorted arrays.cpp
  04. Arrays/find duplicate in an array of N+1 Integers.cpp
Labels: good-first-contribution, hacktoberfest-accepted

#4 add ternarySearch.cpp
  05. Searching/ternarySearch.cpp
Labels: hacktoberfest-accepted

#22 Tourism-Website template added
  34. Front-End Website Templates/Tourism-website/about.html
  34. Front-End Website Templates/Tourism-website/aboutcss.css
  34. Front-End Website Templates/Tourism-website/akhil.png
  34. Front-End Website Templates/Tourism-website/akhil1.png
  34. Front-End Website Templates/Tourism-website/aryan.png
  34. Front-End Website Templates/Tourism-website/avatar.png
  34. Front-End Website Templates/Tourism-website/city1.html
  34. Front-End Website Templates/Tourism-website/city1css.css
  34. Front-End Website Templates/Tourism-website/contact1.html
  34. Front-End Website Templates/Tourism-website/contactcss.css
  34. Front-End Website Templates/Tourism-website/css/style.css
  34. Front-End Website Templates/Tourism-website/gallery2.html
  34. Front-End Website Templates/Tourism-website/gallery2css.css
  34. Front-End Website Templates/Tourism-website/hello.png
  34. Front-End Website Templates/Tourism-website/images/ajmer fort.jpg
  34. Front-End Website Templates/Tourism-website/images/aman temple.jpg
  34. Front-End Website Templates/Tourism-website/images/chittor fort.jpg
  34. Front-End Website Templates/Tourism-website/images/city.jpg
  34. Front-End Website Templates/Tourism-website/images/darjeeling.jpg
  34. Front-End Website Templates/Tourism-website/images/goa.jpg
  34. Front-End Website Templates/Tourism-website/images/golden temple.jpg
  34. Front-End Website Templates/Tourism-website/images/junagardh fort.jpg
  34. Front-End Website Templates/Tourism-website/images/kashi.jpg
  34. Front-End Website Templates/Tourism-website/images/kochi fort.jpg
  34. Front-End Website Templates/Tourism-website/images/manali-tourism.jpg
  34. Front-End Website Templates/Tourism-website/images/pench natural park.jpg
  34. Front-End Website Templates/Tourism-website/images/purana kila.jpg
  34. Front-End Website Templates/Tourism-website/images/ramoji film city.jpg
  34. Front-End Website Templates/Tourism-website/images/red fort.jpg
  34. Front-End Website Templates/Tourism-website/images/somnath temple.jpg
  34. Front-End Website Templates/Tourism-website/images/taj.jpg
  34. Front-End Website Templates/Tourism-website/images/vembanad lake.jpg
  34. Front-End Website Templates/Tourism-website/images/virupaksh temple.jpg
  34. Front-End Website Templates/Tourism-website/images/yamunotri.jpg
  34. Front-End Website Templates/Tourism-website/index.html
  34. Front-End Website Templates/Tourism-website/kaushal.png
  34. Front-End Website Templates/Tourism-website/login.html
  34. Front-End Website Templates/Tourism-website/logo.png
Labels: good first issue, hacktoberfest, good-first-contribution, hacktoberfest-accepted
